[openstack_host]
target1 ansible_host=10.8.130.75 ansible_user=root

[deployer_node]
deployer_local ansible_host=10.8.129.146 ansible_user=root

[all:vars]
ansible_python_interpreter=/usr/bin/python3
