[DEFAULT]
debug = True
log_name = safir_monitoring

[keystone_authtoken]
auth_url = http://10.8.132.48/identity
auth_type = password
username = admin
user_domain_id = default
password = admin
project_name = admin
project_domain_id = default
interface = public
region_name = RegionOne
www_authenticate_uri = http://10.8.132.48/identity
service_token_roles_required = True
service_token_roles = admin

[api_server]
host = 10.8.132.48
port = 9768

[database]
connection = mysql+pymysql://safir_monitoring:admin@10.13.0.10:3306/safir_monitoring?charset=utf8
db_debug = True

[operation_1]
key_prefix = prefix_
value_prefix = prefix_

[operation_2]
key_postfix = postfix_
value_postfix = postfix_

[opensearch]
url = https://10.13.6.5:9200
username = safircloudwatcher
password = zerQrHqam5jwGG0

[email_notifier]
smtp_from = safir.iletisim@tubitak.gov.tr
smtp_host = mta.tubitak.gov.tr:587
smtp_user = safir.iletisim
smtp_pass = BYNFKVATUWSSGWBE

[thanos]
querier_endpoint = http://10.13.0.10:10903
rules_dir = /var/lib/thanos/rules