---
# ==============================================================================
# SafirMonitoring Role - Default Variables
# ==============================================================================

safirmonitoring_gunicorn_workers: 2
safirmonitoring_gunicorn_reuse_port: "False"
safirmonitoring_health_endpoint: "/healthcheck"
sm_ct: "{{ safirmonitoring_container_name }}"
